name: "Pyinstaller build and release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: "Get version"
        id: get_version
        uses: battila7/get-version-action@v2
      
      - name: "Create release"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ServerCreator - $ {{ steps.get_version.outputs.version }}
          body: |
            Server Creator ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

  build:
    runs-on: windows-latest

    needs:
      - release
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"

      - name: "Install requirements"
        run: "pip install -r requirements.txt"
      - name: "Compile exe file"
        run: "pyinstaller servercreator.py --onefile -n ServerCreator.exe"

      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "Compiled files"
          path: |
            build/
            dist/ServerCreator.exe
            ServerCreator.spec
          if-no-files-found: warn
      
      - name: "Upload Comipled file to release page"
        uses: AButler/upload-release-assets@v2
        with:
          file: "dist/ServerCreator.exe"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.get_version.outputs.version }}