name: "Build check"

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"

      - name: "Install requirements"
        run: "pip install -r requirements.txt"
      - name: "Compile exe file"
        run: "pyinstaller servercreator.py --onefile -n ServerCreator.exe"

      - uses: actions/upload-artifact@v3
        with:
          name: "Compiled files"
          path: "dist/ServerCreator.exe"
