name: "Build check"

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"
        
      - run: pip install -r requirements.txt
      - run: pyinstaller servercreator.py --onefile -n ServerCreator

      - uses: actions/upload-artifact@v3
        with:
          name: "Compiled file"
          path: "ServerCreator.exe"